language: java
jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -lukyakha@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
    global:
      - CODECOV_TOKEN="805d4dfd-ccba-4da5-a4f2-f60632b5e175"